# Generated by Django 5.0.6 on 2024-06-03 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_Name', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('Price', models.PositiveIntegerField()),
                ('Date', models.DateField()),
                ('Bus_Type', models.CharField(default='AC', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_Name', models.CharField(default=None, max_length=100)),
                ('Age', models.PositiveIntegerField(default=0)),
                ('Gender', models.CharField(default=None, max_length=100)),
                ('Bus_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buses.buses')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.PositiveIntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Ticket_No', models.PositiveIntegerField(default=0)),
                ('Bus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buses.buses')),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
